# Changes here will be overwritten by Copier
_commit: 002d6bb
_src_path: ./pypackage-template
add_me_as_contributor: false
copyright_year: '2024'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_username: 34j
has_cli: false
initial_commit: false
open_source_license: MIT
open_with_vscode: false
package_name: torchsphharm
project_name: Torchsphharm
project_short_description: Python package for spherical harmonics (sph_harm) in torch
project_slug: torchsphharm
run_poetry_install: false
setup_github: false
setup_pre_commit: false
setup_venv: false
venv_version: '3.11'

